BackendBundle\Entity\Course:
    type: entity
    table: courses
    indexes:
        fk_courses_users:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        startdate:
            type: datetime
            nullable: true
        enddate:
            type: datetime
            nullable: true
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        numClass:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: num_class
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
